# Generated by Django 3.1.7 on 2021-02-25 14:02

import apps.acl.mixin
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('acl', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ACL',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            bases=(models.Model, apps.acl.mixin.RenderMixin),
        ),
        migrations.CreateModel(
            name='ADLSDirectory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('literal_path', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('object_id', models.CharField(max_length=80)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='GroupPermission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access', models.CharField(max_length=3)),
                ('default', models.BooleanField(default=False)),
                ('acl', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='acl.acl')),
                ('group', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='acl.group')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('object_id', models.CharField(max_length=80)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UserPermission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access', models.CharField(max_length=3)),
                ('default', models.BooleanField(default=False)),
                ('acl', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='acl.acl')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='acl.user')),
            ],
        ),
        migrations.DeleteModel(
            name='Principal',
        ),
        migrations.AddConstraint(
            model_name='adlsdirectory',
            constraint=models.UniqueConstraint(fields=('literal_path',), name='unique_directory'),
        ),
        migrations.AddField(
            model_name='acl',
            name='adls_directory',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='acl.adlsdirectory'),
        ),
        migrations.AddConstraint(
            model_name='acl',
            constraint=models.UniqueConstraint(fields=('adls_directory',), name='unique_acl'),
        ),
    ]
