# Generated by Django 3.1.7 on 2021-02-25 14:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('acl', '0002_auto_20210225_1402'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grouppermission',
            name='acl',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_permissions', to='acl.acl'),
        ),
        migrations.AlterField(
            model_name='userpermission',
            name='acl',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_permissions', to='acl.acl'),
        ),
    ]
